language: csharp
solution: Calculator.sln
sudo: required
mono: 
  - latest 
script:
  - xbuild /p:Configuration=Debug Calculator.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nunit-console Calculator.Tests/bin/Debug/Calculator.Tests.dll
after_script:
 - nuget restore Calculator.sln


