language: csharp
solution: Calculator.sln
sudo: required
mono:
  - latest
  - 3.12.0
  - 3.10.0
install:
 - nuget restore Calculator.sln
 - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Calculator.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./MyPoject.Tests/bin/Release/MyProject.Tests.dll
