language: csharp
solution: Calculator.sln
sudo: required
mono: 
  - latest 
script:
  - xbuild /p:Configuration=Debug Calculator.sln
  - nunit-console Calculator.Tests/bin/Debug/Calculator.Tests.dll

  

 


